// <auto-generated />
using System;
using API_CONDOMINIO_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_CONDOMINIO_V2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240617014225_addfirstmodels")]
    partial class addfirstmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Block", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("NameBlock")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<int>("QuantityFloor")
                        .HasColumnType("integer")
                        .HasColumnName("QuantityFloor");

                    b.Property<int>("QuantityeUnit")
                        .HasColumnType("integer")
                        .HasColumnName("QuantityeUnit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NameBlock" }, "IX_NameBlock")
                        .IsUnique();

                    b.ToTable("Block", (string)null);
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 22, 42, 24, 65, DateTimeKind.Local).AddTicks(90))
                        .HasColumnName("CreationDate");

                    b.Property<bool>("Defaulter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Defaulter");

                    b.Property<bool>("DisabledPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("DisabledPerson");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("Excluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Excluded");

                    b.Property<DateTime>("ExclusionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ExclusionDate");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NumberUnit");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Observation");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Phone");

                    b.Property<bool>("Responsible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Responsible");

                    b.Property<short>("SexId")
                        .HasColumnType("smallint");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SexId");

                    b.HasIndex("UnitId");

                    b.ToTable("Resident", (string)null);
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            Slug = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "operacional",
                            Slug = "operacional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "usuario",
                            Slug = "usuario"
                        });
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Sex", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sex");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BlockId")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasGarage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("HasGarage");

                    b.Property<int>("NumberUnit")
                        .HasColumnType("integer")
                        .HasColumnName("NumberUnit");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Observation");

                    b.Property<bool>("PeopleLiving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("PeopleLiving");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Resident", b =>
                {
                    b.HasOne("API_CONDOMINIO_2.Models.Sex", "Sex")
                        .WithMany("Residents")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sex_Residents");

                    b.HasOne("API_CONDOMINIO_2.Models.Unit", "Unit")
                        .WithMany("Residents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Unit_Residents");

                    b.Navigation("Sex");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Unit", b =>
                {
                    b.HasOne("API_CONDOMINIO_2.Models.Block", "Block")
                        .WithMany("Units")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Block_Units");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("API_CONDOMINIO_2.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_RoleId");

                    b.HasOne("API_CONDOMINIO_2.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_UserId");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Block", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Sex", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("API_CONDOMINIO_2.Models.Unit", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
